#!/bin/sh

if [ "$EUID" -ne 0 ] ; then
    echo "This script must be run as root."
    exit
elif [ "$1" == "" ] ; then
    echo "No target destination given."
    exit
fi

SHELL=''

if [ "$2" != "" ] ; then
    SHELL=$2
else
    SHELL='/bin/bash'
fi

mount -t proc proc $1/proc
mount -t sysfs sys $1/sys
if [ ! -z '/sys/firmware/efi/efivars' ] ; then
        mount -t efivarfs efivars $1/sys/firmware/efi/efivars
fi
mount -o bind /dev $1/dev
mount -o bind /etc/resolv.conf $1/etc/resolv.conf

echo 'Entering chroot'
SHELL=$SHELL unshare --fork --pid \
    chroot $1 /usr/bin/env -i HOME=/root \
                              TERM="$TERM" \
                              PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin \
                              PS1='(chroot) \w > ' \
                              $SHELL

echo 'Cleaning up'
umount $1/proc
umount -R $1/sys
umount $1/dev
umount $1/etc/resolv.conf
